### ISSUE TITLE
Error when creating a new project using a template

### ISSUE THREAD

**Issue by nabor** [superpowers/superpowers-core#112]
Platform: Ubuntu 14.04
Node version: 5.6.0

The server crashes with the following error

```
Error: ENOENT: no such file or directory, open '/home/nabor/superpowers/core/server/home/nabor/superpowers/core/systems/game/public/templates/platformer-2d/manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Socket.RemoteHubClient.onAddProject (/home/nabor/superpowers/core/server/RemoteHubClient.js:24:47)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at Socket.onevent (/home/nabor/superpowers/core/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/nabor/superpowers/core/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/nabor/superpowers/core/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/nabor/superpowers/core/node_modules/component-emitter/index.js:134:20)
2/15/2016 11:12:47 AM - Error: ENOENT: no such file or directory, open '/home/nabor/superpowers/core/server/home/nabor/superpowers/core/systems/game/public/templates/platformer-2d/manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Socket.RemoteHubClient.onAddProject (/home/nabor/superpowers/core/server/RemoteHubClient.js:24:47)
    at emitTwo (events.js:100:13)
    at Socket.emit (events.js:185:7)
    at Socket.onevent (/home/nabor/superpowers/core/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/home/nabor/superpowers/core/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/home/nabor/superpowers/core/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/home/nabor/superpowers/core/node_modules/component-emitter/index.js:134:20)
```
It adds the template path to the server path

**Comment by elisee** [comment]
Thanks for the report! Fixed in f616b2ff3c21f54b8559bc2979888e6d439f57a6.
