### ISSUE TITLE
Assets._load: TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by mk-pmb** [superpowers/superpowers-core#120]
When launching the IDE, the log below the "Servers" page shows:

```text
The server crashed while loading project "…".
TypeError: Cannot read property 'data' of undefined
    at Assets._load (…/sph/resources/app/SupCore/Data/Assets.js:25:44)
    at Assets.Dictionary.acquire (…/sph/resources/app/SupCore/Data/Base/Dictionary.js:33:29)
    at Assets.acquire (…/sph/resources/app/SupCore/Data/Assets.js:20:34)
    at …/sph/resources/app/server/ProjectServer.js:227:35
    at …/sph/resources/app/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (…/sph/resources/app/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (…/sph/resources/app/node_modules/async/lib/async.js:209:22)
    at ProjectServer.prepareAssets (…/sph/resources/app/server/ProjectServer.js:221:19)
    at …/sph/resources/app/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (…/sph/resources/app/node_modules/async/lib/async.js:262:13)
```

First step to debugging would be a better error message. My node is too old to build the dev version and make a proper PR, so here's my patch:

```diff
--- resources/app/SupCore/Data/Assets.js.v0.19.0
+++ resources/app/SupCore/Data/Assets.js
@@ -21,8 +21,9 @@
     };
     Assets.prototype._load = function (id) {
         var _this = this;
         var entry = this.server.data.entries.byId[id];
+        if (!this.server.system) { throw new Error("No server.system?"); }
         var assetClass = this.server.system.data.assetClasses[entry.type];
         if (assetClass == null)
             throw new Error("No data plugin for asset type \"" + entry.type + "\"");
         var asset = new assetClass(id, null, this.server);
```

Launching the IDE again shows that this was the problem:

```text
The server crashed while loading project "…".
Error: No server.system?
    at Assets._load (…/sph/resources/app/SupCore/Data/Assets.js:25:42)
```

I hope the docs will tell me where to get a proper `server.system`.

**Comment by elisee** [comment]
Are you trying to load an old demo project (can you link it, if os)? Or an old project of yours?

**Comment by mk-pmb** [comment]
The game I tried to load was [love2d-shooter-game](https://github.com/superpowers-extra/love2d-shooter-game.git) @ ccb754b2dac18cc7eaece8a46af7aa91ce6e7812 (Thu 2016-01-28 16:57), working directory clean.

**Comment by elisee** [comment]
Thanks for the report. As you mentioned in https://github.com/superpowers/superpowers-core/issues/123, the development version now crashes with a proper message that says `Error: The system [...] is not installed.` so I think we can close this one.
